name: ci


on:
  push:
    tags: ["v*"]
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up dotnet
      if: ${{ contains(matrix.os, 'ubuntu') }}
      uses: actions/setup-dotnet@v4

    - name: building executables
      run: chmod +x ./build.sh && ./build.sh

    - name: Display structure of builded files
      run: ls -R ./publish/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: SocksToVPN_build_files
        path: ./publish
        if-no-files-found: error
        retention-days: 2
        compression-level: 8
        overwrite: true

    - name: Move into one directory
      run: chmod +x ./move_build_files.sh && ./move_build_files.sh

    - name: Release
      if: ${{ startsWith(github.ref, 'refs/tags/v') && !contains(github.ref, '-') }}
      uses: softprops/action-gh-release@v1
      with:
        files: combined_files/*
        fail_on_unmatched_files: true
        append_body: true
